swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /v1

# Paths supported by the server application
paths:
  /users:
    get:
      operationId: database.fetchByQuery("public.user")
      #operationId: users.read_all
      tags:
        - Users
      summary: Read users
      description: Read the entire set of users, sorted by last name
      responses:
        200:
          description: Successfully read users set operation
          schema:
            type: array
            items:
              properties:
                user_id:
                  type: string
                  description: id of the user
                fname:
                  type: string
                  description: First name of the user
                lname:
                  type: string
                  description: Last name of the user
                timestamp:
                  type: string
                  description: Creation/Update timestamp of the user

    post:
      operationId: users.create
      tags:
        - Users
      summary: Create a user
      description: Create a new user in users list
      parameters:
        - name: user
          in: body
          description: User to create
          required: True
          schema:
            type: object
            properties:
              fname:
                type: string
                description: First name of user to create
              lname:
                type: string
                description: Last name of user to create
      responses:
        201:
          description: Successfully created user
          schema:
            properties:
              user_id:
                type: string
                description: id of the user
              fname:
                type: string
                description: First name of the user
              lname:
                type: string
                description: Last name of the user
              timestamp:
                type: string
                description: Creation/Update timestamp of the user record

  /users/{user_id}:
    get:
      operationId: users.read_one
      tags:
        - Users
      summary: Read one user
      description: Read one user from the users list
      parameters:
        - name: user_id
          in: path
          description: id of the user to get from the list
          type: integer
          required: True
      responses:
        200:
          description: Successfully read user from users data operation
          schema:
            type: object
            properties:
              user_id:
                type: string
                description: id of the user
              fname:
                type: string
                description: First name of the user
              lname:
                type: string
                description: Last name of the user
              timestamp:
                type: string
                description: Creation/Update timestamp of the user record

    put:
      operationId: users.update
      tags:
        - Users
      summary: Update a user
      description: Update a user in the users list
      parameters:
        - name: user_id
          in: path
          description: id of the user to update
          type: integer
          required: True
        - name: user
          in: body
          schema:
            type: object
            properties:
              fname:
                type: string
                description: First name of the user
              lname:
                type: string
                description: Last name of the user
      responses:
        200:
          description: Successfully updated user in users list
          schema:
            properties:
              user_id:
                type: string
                description: id of the user in the database
              fname:
                type: string
                description: First name of the user
              lname:
                type: string
                description: Last name of the user
              timestamp:
                type: string
                description: Creation/Update timestamp of the user record

    delete:
      operationId: users.delete
      tags:
        - Users
      summary: Delete a user
      description: Delete a user from the users list
      parameters:
        - name: user_id
          in: path
          type: integer
          description: id of the user to delete
          required: true
      responses:
        200:
          description: Successfully deleted a user
